<a href="https://colab.research.google.com/github/HeHeHuang/Python_Alg_Stc/blob/main/Daily_Clarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 2022-08-30

#### figure out how to print each word newline

In [ ]:
sentence = 'I love Python'
list_sentence = sentence.split(' ')
for i in list_sentence:
  print(i,end='') # default is new line '\n'

IlovePython

In [ ]:
sentence.lower().strip()

'i love python'

### 2022-08-31

In [4]:
import numpy as np 
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
s = [s for s in range(20)]
s[::2]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
s[::3]

[0, 3, 6, 9, 12, 15, 18]

In [12]:
p= np.zeros(shape=(3,8))
p

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
p[:,::2] =  np.arange(0,8,2)

In [20]:
p

array([[0., 0., 2., 0., 4., 0., 6., 0.],
       [0., 0., 2., 0., 4., 0., 6., 0.],
       [0., 0., 2., 0., 4., 0., 6., 0.]])

##### word embedding in tensorflow


In [25]:
docs = ['Well done!',
		'Good work',
		'good work',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

#### one hot encoding 
> one_hot() arrange the word index 

In [26]:
from keras.preprocessing.text import one_hot
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[2, 21], [30, 31], [30, 31], [49, 31], [8], [24], [31, 29], [13, 30], [31, 31], [46, 38, 21, 4]]


In [27]:
import numpy as np
import matplotlib.pyplot as plt
 
def getPositionEncoding(seq_len, d, n=10000):
    P = np.zeros((seq_len, d))
    for k in range(seq_len):
        for i in np.arange(int(d/2)):
            denominator = np.power(n, 2*i/d)
            P[k, 2*i] = np.sin(k/denominator)
            P[k, 2*i+1] = np.cos(k/denominator)
    return P
 
P = getPositionEncoding(seq_len=4, d=4, n=100)
print(P)

[[ 0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.09983342  0.99500417]
 [ 0.90929743 -0.41614684  0.19866933  0.98006658]
 [ 0.14112001 -0.9899925   0.29552021  0.95533649]]
